# Generated by Django 2.0.6 on 2018-06-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='img_url',
        ),
        migrations.AddField(
            model_name='piece',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='piece_images'),
        ),
    ]
