# Generated by Django 2.0.6 on 2018-06-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180616_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='img_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='profile_images'),
        ),
    ]
