# Generated by Django 2.0.6 on 2018-06-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20180616_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='image',
            field=models.ImageField(default='default.png', upload_to='piece_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_images'),
        ),
    ]
