# Generated by Django 2.0.6 on 2018-06-21 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20180616_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='piece',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Piece'),
            preserve_default=False,
        ),
    ]
