# Generated by Django 2.0.6 on 2018-06-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_post_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='delete',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
