# Generated by Django 2.0.6 on 2018-06-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_piece_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='delete',
            field=models.NullBooleanField(),
        ),
    ]
