# Generated by Django 2.0.6 on 2018-06-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20180621_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
