# Generated by Django 2.0.6 on 2018-06-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_post'),
        ('main_app', '0012_auto_20180622_0042'),
    ]

    operations = [
    ]
